parameters:
#    anton_user.example.class: Anton\UserBundle\Example

services:
#    anton_user.example:
#        class: %anton_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
